spring:
  profiles:
    active:
    - dev

---

server:
  port: 8001
spring:
  profiles: dev
  application:
    name: MicroServiceCloud-Config-Dept-Client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?characterEncoding=utf8&useSSL=true&rewriteBatchedStatements=true #mysql驱动包
    # 数据库名称
    username: root
    password: deak1991
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200

#mybatis整合
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.xsquare.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mappers/**/*.xml

eureka:
  client: #客户端注册进eureka的服务列表
    service-url:
      # 单机版：defaultZone: http://localhost:7001/eureka #服务端提供的地址
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001 #修改实例id
    prefer-ip-address: true #点击实例访问路径可以显示ip


info:
  app.name: xsquare-microservicecloud
  company.name: www.xsquare.cn
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"

---

server:
  port: 8001
spring:
  profiles: test
  application:
    name: MicroServiceCloud-Config-Dept-Client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02?characterEncoding=utf8&useSSL=true&rewriteBatchedStatements=true #mysql驱动包
    # 数据库名称
    username: root
    password: deak1991
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200

#mybatis整合
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.xsquare.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mappers/**/*.xml

eureka:
  client: #客户端注册进eureka的服务列表
    service-url:
      # 单机版：defaultZone: http://localhost:7001/eureka #服务端提供的地址
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001 #修改实例id
    prefer-ip-address: true #点击实例访问路径可以显示ip


info:
  app.name: xsquare-microservicecloud
  company.name: www.xsquare.cn
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"
