server:
  port: 8201
sprint:
  profiles: dev
  application:
    name: MicroServiceCloud-Config-Client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/

---

server:
  port: 8202
sprint:
  profiles: test
  application:
    name: MicroServiceCloud-Config-Client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/